# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
device_target: "Ascend"
device_id: 0
enable_profiling: False
model: "src/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/3d_fullres/Task004_Hippocampus/nnUNetTrainerV2__nnUNetPlansv2.1"
checkpoint_file: "model_best"
# ==============================================================================
# export options
air_name: 'nnUNet_3d_fullres'
model_name: nnUNet_3d_fullres
file_name: 'nnUNet_3d_fullres'
file_format: 'MINDIR'
batch_size: 9
channel: 1
depth: 40
height: 56
width: 40
dataset_name: 'Task004_Hippocampus'
